# Meta
description: Private theme for artifact.me
keywords: hexo,theme,artifact,otakism

# Author
author_avatar: /img/avatar3.png

# Search
search: 
  enable: 
  service: hexo # swiftype/google/hexo/algolia/azure
  # google 
  google_api_key: 
  google_engine_id: 
  # algolia
  algolia_app_id: 
  algolia_api_key: 
  algolia_index_name: 
  # azure
  azure_service_name: 
  azure_index_name: 
  azure_query_key: 

# Miscellaneous
google_analytics: UA-120534070-1
# favicon: /favicon.png
favicon: /img/avatar3.png

# Less
less:
  compress: true

# use url, not username
social:
- name: feed
	url: /atom.xml
- name: email
  url: 
- name: github
  url: https://github.com/micchi-fms
- name: twitter
  url: 
- name: google
  url: 
- name: facebook
  url: 
- name: linkedin
  url: 
- name: weibo
  url: 
- name: tumblr
  url: 
- name: dribbble
  url: 
- name: pinterest
  url: 
- name: instagram
  url: 
- name: behance
  url: 
